### ISSUE TITLE
No way to specify output format/codec for static file processing

### ISSUE THREAD

**Issue by gregdumb** [gregdumb/cs160#14]
Ideal solution: `cvprocessor -f [blah] -ffmpegout "string of ffmpeg output parameters" ` (from @deanljohnson on Discord)

**Comment by deanljohnson** [comment]
Resolved. Can pass "-of", stands for 'output format', to specify output parameters. Defaults to "-f webm -c:v vp8 -b:v .5M".

Ex:
./cvprocessor -f test.webm -of "-f webm -c:v vp8 -b:v .5M"
